/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AdminBorrow {
    }
    interface AdminHome {
    }
    interface AdminLogin {
    }
    interface AdminRequest {
    }
    interface AdminReturn {
    }
    interface AdminSignup {
    }
    interface ClientBorrow {
    }
    interface ClientHome {
    }
    interface ClientLogin {
    }
    interface ClientRequest {
    }
    interface ClientReturn {
    }
    interface ClientSignup {
    }
    interface FeaturesSection {
    }
    interface FooterSection {
    }
    interface HeroSection {
    }
    interface MyNav {
        "firstHref": string;
        "firstOption": string;
        "logOut": string;
        "secondHref": string;
        "secondOption": string;
    }
    interface RootApp {
    }
}
declare global {
    interface HTMLAdminBorrowElement extends Components.AdminBorrow, HTMLStencilElement {
    }
    var HTMLAdminBorrowElement: {
        prototype: HTMLAdminBorrowElement;
        new (): HTMLAdminBorrowElement;
    };
    interface HTMLAdminHomeElement extends Components.AdminHome, HTMLStencilElement {
    }
    var HTMLAdminHomeElement: {
        prototype: HTMLAdminHomeElement;
        new (): HTMLAdminHomeElement;
    };
    interface HTMLAdminLoginElement extends Components.AdminLogin, HTMLStencilElement {
    }
    var HTMLAdminLoginElement: {
        prototype: HTMLAdminLoginElement;
        new (): HTMLAdminLoginElement;
    };
    interface HTMLAdminRequestElement extends Components.AdminRequest, HTMLStencilElement {
    }
    var HTMLAdminRequestElement: {
        prototype: HTMLAdminRequestElement;
        new (): HTMLAdminRequestElement;
    };
    interface HTMLAdminReturnElement extends Components.AdminReturn, HTMLStencilElement {
    }
    var HTMLAdminReturnElement: {
        prototype: HTMLAdminReturnElement;
        new (): HTMLAdminReturnElement;
    };
    interface HTMLAdminSignupElement extends Components.AdminSignup, HTMLStencilElement {
    }
    var HTMLAdminSignupElement: {
        prototype: HTMLAdminSignupElement;
        new (): HTMLAdminSignupElement;
    };
    interface HTMLClientBorrowElement extends Components.ClientBorrow, HTMLStencilElement {
    }
    var HTMLClientBorrowElement: {
        prototype: HTMLClientBorrowElement;
        new (): HTMLClientBorrowElement;
    };
    interface HTMLClientHomeElement extends Components.ClientHome, HTMLStencilElement {
    }
    var HTMLClientHomeElement: {
        prototype: HTMLClientHomeElement;
        new (): HTMLClientHomeElement;
    };
    interface HTMLClientLoginElement extends Components.ClientLogin, HTMLStencilElement {
    }
    var HTMLClientLoginElement: {
        prototype: HTMLClientLoginElement;
        new (): HTMLClientLoginElement;
    };
    interface HTMLClientRequestElement extends Components.ClientRequest, HTMLStencilElement {
    }
    var HTMLClientRequestElement: {
        prototype: HTMLClientRequestElement;
        new (): HTMLClientRequestElement;
    };
    interface HTMLClientReturnElement extends Components.ClientReturn, HTMLStencilElement {
    }
    var HTMLClientReturnElement: {
        prototype: HTMLClientReturnElement;
        new (): HTMLClientReturnElement;
    };
    interface HTMLClientSignupElement extends Components.ClientSignup, HTMLStencilElement {
    }
    var HTMLClientSignupElement: {
        prototype: HTMLClientSignupElement;
        new (): HTMLClientSignupElement;
    };
    interface HTMLFeaturesSectionElement extends Components.FeaturesSection, HTMLStencilElement {
    }
    var HTMLFeaturesSectionElement: {
        prototype: HTMLFeaturesSectionElement;
        new (): HTMLFeaturesSectionElement;
    };
    interface HTMLFooterSectionElement extends Components.FooterSection, HTMLStencilElement {
    }
    var HTMLFooterSectionElement: {
        prototype: HTMLFooterSectionElement;
        new (): HTMLFooterSectionElement;
    };
    interface HTMLHeroSectionElement extends Components.HeroSection, HTMLStencilElement {
    }
    var HTMLHeroSectionElement: {
        prototype: HTMLHeroSectionElement;
        new (): HTMLHeroSectionElement;
    };
    interface HTMLMyNavElement extends Components.MyNav, HTMLStencilElement {
    }
    var HTMLMyNavElement: {
        prototype: HTMLMyNavElement;
        new (): HTMLMyNavElement;
    };
    interface HTMLRootAppElement extends Components.RootApp, HTMLStencilElement {
    }
    var HTMLRootAppElement: {
        prototype: HTMLRootAppElement;
        new (): HTMLRootAppElement;
    };
    interface HTMLElementTagNameMap {
        "admin-borrow": HTMLAdminBorrowElement;
        "admin-home": HTMLAdminHomeElement;
        "admin-login": HTMLAdminLoginElement;
        "admin-request": HTMLAdminRequestElement;
        "admin-return": HTMLAdminReturnElement;
        "admin-signup": HTMLAdminSignupElement;
        "client-borrow": HTMLClientBorrowElement;
        "client-home": HTMLClientHomeElement;
        "client-login": HTMLClientLoginElement;
        "client-request": HTMLClientRequestElement;
        "client-return": HTMLClientReturnElement;
        "client-signup": HTMLClientSignupElement;
        "features-section": HTMLFeaturesSectionElement;
        "footer-section": HTMLFooterSectionElement;
        "hero-section": HTMLHeroSectionElement;
        "my-nav": HTMLMyNavElement;
        "root-app": HTMLRootAppElement;
    }
}
declare namespace LocalJSX {
    interface AdminBorrow {
    }
    interface AdminHome {
    }
    interface AdminLogin {
    }
    interface AdminRequest {
    }
    interface AdminReturn {
    }
    interface AdminSignup {
    }
    interface ClientBorrow {
    }
    interface ClientHome {
    }
    interface ClientLogin {
    }
    interface ClientRequest {
    }
    interface ClientReturn {
    }
    interface ClientSignup {
    }
    interface FeaturesSection {
    }
    interface FooterSection {
    }
    interface HeroSection {
    }
    interface MyNav {
        "firstHref"?: string;
        "firstOption"?: string;
        "logOut"?: string;
        "secondHref"?: string;
        "secondOption"?: string;
    }
    interface RootApp {
    }
    interface IntrinsicElements {
        "admin-borrow": AdminBorrow;
        "admin-home": AdminHome;
        "admin-login": AdminLogin;
        "admin-request": AdminRequest;
        "admin-return": AdminReturn;
        "admin-signup": AdminSignup;
        "client-borrow": ClientBorrow;
        "client-home": ClientHome;
        "client-login": ClientLogin;
        "client-request": ClientRequest;
        "client-return": ClientReturn;
        "client-signup": ClientSignup;
        "features-section": FeaturesSection;
        "footer-section": FooterSection;
        "hero-section": HeroSection;
        "my-nav": MyNav;
        "root-app": RootApp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "admin-borrow": LocalJSX.AdminBorrow & JSXBase.HTMLAttributes<HTMLAdminBorrowElement>;
            "admin-home": LocalJSX.AdminHome & JSXBase.HTMLAttributes<HTMLAdminHomeElement>;
            "admin-login": LocalJSX.AdminLogin & JSXBase.HTMLAttributes<HTMLAdminLoginElement>;
            "admin-request": LocalJSX.AdminRequest & JSXBase.HTMLAttributes<HTMLAdminRequestElement>;
            "admin-return": LocalJSX.AdminReturn & JSXBase.HTMLAttributes<HTMLAdminReturnElement>;
            "admin-signup": LocalJSX.AdminSignup & JSXBase.HTMLAttributes<HTMLAdminSignupElement>;
            "client-borrow": LocalJSX.ClientBorrow & JSXBase.HTMLAttributes<HTMLClientBorrowElement>;
            "client-home": LocalJSX.ClientHome & JSXBase.HTMLAttributes<HTMLClientHomeElement>;
            "client-login": LocalJSX.ClientLogin & JSXBase.HTMLAttributes<HTMLClientLoginElement>;
            "client-request": LocalJSX.ClientRequest & JSXBase.HTMLAttributes<HTMLClientRequestElement>;
            "client-return": LocalJSX.ClientReturn & JSXBase.HTMLAttributes<HTMLClientReturnElement>;
            "client-signup": LocalJSX.ClientSignup & JSXBase.HTMLAttributes<HTMLClientSignupElement>;
            "features-section": LocalJSX.FeaturesSection & JSXBase.HTMLAttributes<HTMLFeaturesSectionElement>;
            "footer-section": LocalJSX.FooterSection & JSXBase.HTMLAttributes<HTMLFooterSectionElement>;
            "hero-section": LocalJSX.HeroSection & JSXBase.HTMLAttributes<HTMLHeroSectionElement>;
            "my-nav": LocalJSX.MyNav & JSXBase.HTMLAttributes<HTMLMyNavElement>;
            "root-app": LocalJSX.RootApp & JSXBase.HTMLAttributes<HTMLRootAppElement>;
        }
    }
}
